import { test, expect } from '@playwright/test'
test('carta completa, precios pendientes y salsas opcionales', async ({ page }) => {
  await page.goto('/?mesa=8')
  await expect(page.locator('.product-card')).toHaveCount(184)
  await expect(page.getByText('Mesa: 8', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pizzas de la Bahía', exact: true }).click()
  const card = page.getByRole('button', { name: 'Ver Merluza Negra, disponible' })
  await expect(card).toContainText('Consultar precio')
  await card.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Pedir en la mesa / Dudas' })).toBeDisabled()
  await dialog.getByRole('radio', { name: /Chico/ }).check()
  await expect(dialog.locator('.modal-price')).toContainText('Consultar precio')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Postres', exact: true }).click()
  await expect(page.locator('.product-card')).toHaveCount(8)
  for (const dessert of await page.locator('.product-card').all())
    await expect(dessert).toContainText('Consultar precio')
  await page.getByRole('button', { name: 'Pastas', exact: true }).click()
  await page.getByRole('button', { name: 'Ver Ñoquis, disponible' }).click()
  await expect(dialog.locator('.modal-price')).toContainText('$16.000')
  await expect(dialog.getByRole('button', { name: 'Pedir en la mesa / Dudas' })).toBeEnabled()
  await dialog.getByRole('radio', { name: /Langostino/ }).check()
  await expect(dialog.locator('.modal-price')).toContainText('$24.000')
  await dialog.getByRole('radio', { name: 'Sin adicional' }).check()
  await expect(dialog.locator('.modal-price')).toContainText('$16.000')
})
test('búsqueda, categorías, modal, foco y WhatsApp con mesa', async ({ page }) => {
  await page.goto('/?mesa=12')
  await expect(page.getByRole('heading', { name: 'El sabor de Ushuaia' })).toBeVisible()
  await page.getByRole('link', { name: 'Ver menú', exact: true }).click()
  await expect(page).toHaveURL(/\?mesa=12#menu$/)
  await page.getByRole('textbox', { name: 'Buscar productos' }).fill('ORÉGANO')
  await expect(page.getByRole('button', { name: 'Ver Muzzarella, disponible' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ver Rabas, disponible' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Borrar búsqueda' }).click()
  await page.getByRole('button', { name: 'Pizzas', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ver Muzzarella, disponible' })).toBeVisible()
  const card = page.getByRole('button', { name: 'Ver Muzzarella, disponible' })
  await card.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  const order = dialog.getByRole('button', { name: 'Pedir en la mesa / Dudas' })
  await expect(order).toBeDisabled()
  await dialog.getByRole('radio', { name: /Grande/ }).check()
  await expect(order).toBeEnabled()
  await expect(dialog.locator('.modal-price')).toContainText('$19.000')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(card).toBeFocused()
  await card.click()
  await page.mouse.click(10, 10)
  await expect(dialog).toHaveCount(0)
})
test('rutas administrativas requieren sesión y no simulan login', async ({ page }) => {
  await page.goto('/admin/productos')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('button', { name: 'Ingresar al administrador' })).toBeDisabled()
  await expect(page.getByText('Modo demostración.', { exact: false })).toBeVisible()
})
for (const width of [320, 390, 768, 1024, 1440])
  test(`diseño sin desbordes a ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'El sabor de Ushuaia' })).toBeVisible()
    expect(
      await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
    ).toBe(true)
    await page.screenshot({ path: `test-results/catalog-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Ver Muzzarella, disponible' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByRole('dialog')).toHaveCSS('opacity', '1')
    const box = await page.getByRole('dialog').boundingBox()
    expect(box!.width).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `test-results/modal-${width}.png` })
    await page.keyboard.press('Escape')
  })
